api_program/urls.py
from django.contrib import admin
from django.urls import path,re_path
from api_project import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',views.User_Login.as_view()),
    path('home/',views.home),
    path('logout/',views.logout),
    path('project/',views.Project.as_view()),
    path('API/',views.API.as_view()),
    path('Interface/',views.Interface.as_view()),
    path('report/',views.Generate_Report),
    path('Interface_set/',views.Interface_set.as_view()),
    re_path('Interface_set/detail/(\d+)',views.detail),
    path('set/',views.set),
    path('start/',views.start_run),
    path('user/',views.User.as_view()),
]

api_project/models.py
from django.db import models
# Create your models here.
class Userinfo(models.Model):
    username=models.CharField(max_length=50)
    password=models.CharField(max_length=50)
    userimage_url=models.CharField(max_length=50)
    usertype=models.CharField(max_length=20)
class Project(models.Model):
    project_name=models.CharField(max_length=30)
    project_ver=models.CharField(max_length=10)
    project_url=models.TextField()
    type=((0,'启用'),(1,'禁用'))
    project_type=models.IntegerField(choices=type)
    create_time=models.DateTimeField(auto_now_add=True)
    project_remark=models.TextField()
class API(models.Model):
    project=models.ForeignKey('Project',on_delete=models.PROTECT)
    API_name=models.CharField(max_length=30)
    API_url=models.TextField()
    API_para=models.TextField()
    API_remark=models.TextField()
    ways=((0,'POST'),(1,'GET'))
    API_way=models.IntegerField(choices=ways)
    create_time = models.DateTimeField(auto_now_add=True)
class interface(models.Model):
   API=models.ForeignKey('API',on_delete=models.PROTECT)
   interface_name=models.CharField(max_length=50)
   interface_result=models.TextField()
   interface_remark=models.TextField()
   interface_rel_result=models.TextField()
   create_time = models.DateTimeField(auto_now_add=True)
class API_result(models.Model):
    reslut_name=models.CharField(max_length=50)
    reslut_remark=models.TextField()
    interface=models.ManyToManyField("interface")

templates/API.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/home.css">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/common.css">
    <link rel="stylesheet" href="/static/css/API.css">
</head>
<body class="home_body">
    <div class="home-header">
        <div class="user-info">{{ username }}
            <div class="user-logout">
                <a href="/logout">退出登录</a>
            </div>
        </div>
        <div class="project-content">
            <div class="project-header">
                <span>项目名称:&nbsp&nbsp</span>
                <select   name="query_project" style="min-width: 150px;min-height: 25px">
                {% for i in project_name %}
                    <option value="{{ i.id }}"> {{ i.project_name }}</option>
                {% endfor %}
                </select>
                <span>接口名称&nbsp&nbsp</span><input type="text" placeholder="请输入接口名称名称" name="query_API">
                <input type="button" value="查询" id="project-q">
                <input class="API-new" type="button" value="新增接口" >
            </div>
            <div class="project-table">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>序号</th>
                            <th>所属项目</th>
                            <th>接口名称</th>
                            <th>接口地址</th>
                            <th>接口参数</th>
                            <th>接口描述</th>
                            <th>接口方式</th>
                            <th>修改时间</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in API %}
                            <tr API-id={{ i.id }}>
                                <td>{{ forloop.counter}}</td>
                                <td project-id={{ i.project_id }}>{{ i.project.project_name}}</td>
                                <td>{{ i.API_name }}</td>
                                <td>{{ i.API_url }}</td>
                                <td>{{ i.API_para }}</td>
                                <td>{{ i.API_remark }}</td>
                                <td>{{ i.get_API_way_display }}</td>
                                <td>{{ i.create_time|date:"Y.m.d" }}</td>
                                <td type-id={{ i.API_way }}>
                                    <a class="API-edit">编辑</a>
                                    <a class="API-delete">删除</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="home-pagination">
                <span class="step-links">
                    <span class="current" >共{{ API.paginator.num_pages }}页</span>
                    {% if API.has_previous %}
                        <a href="?page={{ API.previous_page_number }}">上一页</a>
                    {% endif %}
                    <span >
                        第 {{ API.number }} 页
                    </span>
                    {% if API.has_next %}
                        <a href="?page={{ API.next_page_number }}">下一页</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
    <div class="home_menu">
        <div class="home-title">
           接口测试管理平台
        </div>
        <div class="home-lines">
            <a  href="/project/">项目管理</a>
            <a class="active">接口管理</a>
            <a href="/Interface/">测试用例管理</a>
            <a href="/Interface_set/">测试报告管理</a>
            <a>用户管理</a>
        </div>
    </div>
    <div class="home-show hide">
        <div class="API-alert hide"></div>
    </div>
    <div class="API-modal hide">
        <form id="API-add">
            <div class="API-add-title">新增接口</div>
            <div class="API-input-comomn">
            <span class="API-sapn">所属项目:</span><select name="project_name" style="min-width: 200px; min-height: 30px;margin-left: 10px;margin-top: 10px">
                {% for r in project_name %}
                <option value="{{ r.id }}" >{{ r.project_name }}</option>
                {% endfor %}
            </select>
             <span class="API-sapn">接口名称:</span><input  class="API-input" type="text" name="API_name">
            </div>
            <input type="hidden" name="API-id">
            <div class="API-input-comomn">
                <span class="API-sapn">接口地址:</span><input  class="API-input" type="text" name="API_url">
                <span class="API-sapn">接口方式:</span><select name="API_way" style="min-width: 200px; min-height: 30px;margin-left: 10px;margin-top: 10px">
                <option value="0">POST</option>
                <option value="1">GET</option>
                </select>
            </div>
            <div class="API-textarea">
                <span class="API-sapn">接口参数:</span><textarea class="textarea" name="API_para" placeholder="请输入字典格式数据"></textarea>
            </div>
            <div class="API-textarea">
                <span class="API-sapn">接口描述:</span><textarea class="textarea"  name="API_remark"></textarea>
            </div>
            <div class="API-button">
                <input type="button" class="api-button" value="确定">
                <input type="button" class="api-button" value="取消">
            </div>
        </form>
    </div>
    <div class="API-para hide">
        <div class="modal-header">
            <strong>接口token</strong>
        </div>
        <div>
            <input class="form-control" type="text" placeholder="请输入token" name="API-token">
        </div>
        <div class="modal-footer">
            <input class="btn btn-default" type="button" value="确定">
            <input class="btn btn-primary" type="button" value="取消">
        </div>
    </div>
    <script src="/static/js/jquery-1.12.4.js"></script>
    <script src="/static/js/API.js"></script>
    <script src="/static/js/project.js"></script>
</body>
</html>

templates/Interface.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/home.css">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/common.css">
    <link rel="stylesheet" href="/static/css/API.css">
    <link rel="stylesheet" href="/static/css/Interface.css">
</head>
<body class="home_body">
    <div class="home-header">
        <div class="user-info">{{ username }}
            <div class="user-logout">
                <a href="/logout">退出登录</a>
            </div>
        </div>
        <div class="project-content">
            <div class="project-header">
                <span>接口名称:&nbsp&nbsp</span>
                <select   name="API_query" style="min-width: 150px;min-height: 25px">
                {% for i in API %}
                    <option value="{{ API.id }}"> {{ i.API_name }}</option>
                {% endfor %}
                </select>
                <span>用例名称&nbsp&nbsp</span><input type="text" placeholder="请输入用例名称" name="query_Interface_name">
                <input type="button" value="查询" id="project-q">
                <input class="Interface-new" type="button" value="新增用例" >
            </div>
            <div class="project-table">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>序号</th>
                            <th>所属项目</th>
                            <th>所属接口</th>
                            <th>用例名称</th>
                            <th>用例描述</th>
                            <th>预期结果</th>
                            <th>测试结果</th>
                            <th>最近测试时间</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in Interface %}
                            <tr Interface-id={{ i.id }}>
                                <td>{{ forloop.counter}}</td>
                                <td project_id={{ i.API.project_id }}>{{ i.API.project.project_name }}</td>
                                <td API_id={{ i.API_id }}>{{ i.API.API_name}}</td>
                                <td>{{ i.interface_name }}</td>
                                <td>{{ i.interface_remark }}</td>
                                <td>{{ i.interface_result|truncatechars:10 }}</td>
                                <td>{{ i.interface_rel_result }}</td>
                                <td>{{ i.create_time|date:"Y.m.d" }}</td>
                                <td >
                                    <a class="API_do">执行</a>
                                    <a class="interface-edit">编辑</a>
                                    <a class="interface-delete">删除</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="home-pagination">
                <span class="step-links">
                    <span class="current" >共{{ Interface.paginator.num_pages }}页</span>
                    {% if Interface.has_previous %}
                        <a href="?page={{ Interface.previous_page_number }}">上一页</a>
                    {% endif %}
                    <span >
                        第 {{ Interface.number }} 页
                    </span>
                    {% if Interface.has_next %}
                        <a href="?page={{ Interface.next_page_number }}">下一页</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
    <div class="home_menu">
        <div class="home-title">
           接口测试管理平台
        </div>
        <div class="home-lines">
            <a  href="/project/">项目管理</a>
            <a href="/API/">接口管理</a>
            <a class="active">测试用例管理</a>
            <a href="/Interface_set/">测试报告管理</a>
            <a>用户管理</a>
        </div>
    </div>
    <div class="home-show hide">
        <div class="interface-alert hide"></div>
    </div>
    <div class="Interface-modal hide">
        <form id="Interface" class="interface-form">
            <input type="hidden" name="interface_id">
            <h4 class="interface-title" style="text-align: center;">新增用例</h4>
            <div class="interface-input">
                <label>请选择所属接口:</label><select class="select-common" name="API_name">
                    {% for r in API %}
                        <option value= "{{ r.id }}">{{ r.API_name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="interface-input">
              <label>用例名称:</label> <input type="text" name="Interface_name">
            </div>
            <div class="interface-textarea">
                <label>用例描述:</label> <textarea  name="Interface_remark"></textarea>
            </div>
            <div class="interface-textarea">
                <label>预期结果:</label><textarea name="Interface_result"></textarea>
            </div>
            <div class="interface-button">
                <input type="button"  class="interface-a" value="确定">
                <input type="button"  class="interface-b" value="取消">
            </div>
        </form>


    </div>
    <div class="API-para hide">
        <div class="modal-header">
            <strong>接口token</strong>
        </div>
        <div>
            <input class="form-control" type="text" placeholder="请输入token" name="API-token">
        </div>
        <div>
            <strong style="margin-left: 5px">测试结果:</strong><textarea class="form-control" rows="10" cols="43" name="test_result"></textarea>
        </div>
        <div class="modal-footer">
            <input class="btn btn-default" type="button" value="确定">
            <input class="btn btn-primary" type="button" value="关闭">
        </div>
    </div>
    <script src="/static/js/jquery-1.12.4.js"></script>
    <script src="/static/js/API.js"></script>
    <script src="/static/js/project.js"></script>
    <script src="/static/js/Interface.js"></script>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/home.css">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/common.css">
</head>
<body class="home_body">
    <div class="home-header">
        <div class="user-info">{{ username }}
            <div class="user-logout">
                <a href="/logout">退出登录</a>
            </div>
        </div>
        <div class="project-content">
            <div class="project-header">
                <span>项目名称:&nbsp&nbsp</span><input type="text" placeholder="请输入项目名称" name="query_project">
                <input type="button" value="查询" id="project-q">
                <input  class="project-new" type="button" value="新建项目" >
            </div>
            <div class="project-table">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>序号</th>
                            <th>项目名称</th>
                            <th>项目版本</th>
                            <th>项目地址</th>
                            <th>备注</th>
                            <th>状态</th>
                            <th>修改时间</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in project %}
                            <tr project-id={{ i.id }}>
                                <td>{{ forloop.counter}}</td>
                                <td>{{ i.project_name }}</td>
                                <td>{{ i.project_ver }}</td>
                                <td>{{ i.project_url }}</td>
                                <td>{{ i.project_remark }}</td>
                                <td>{{ i.get_project_type_display }}</td>
                                <td>{{ i.create_time|date:"Y.m.d" }}</td>
                                <td p-id={{ i.project_type}}>
                                    {% if i.project_type == 0 %}
                                        <a  class="table-button">停用</a>
                                    {% else %}
                                        <a  class="table-button">启用</a>
                                    {% endif %}
                                    <a  class="table-edit">编辑</a>
                                    <a  class="table-delete">删除</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="home-pagination">
                <span class="step-links">
                    <span class="current" >共{{ project.paginator.num_pages }}页</span>
                    {% if project.has_previous %}
                        <a href="?page={{ project.previous_page_number }}">上一页</a>
                    {% endif %}
                    <span >
                        第 {{ project.number }} 页
                    </span>
                    {% if project.has_next %}
                        <a href="?page={{ project.next_page_number }}">下一页</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
    <div class="home_menu">
        <div class="home-title">
           接口测试管理平台
        </div>
        <div class="home-lines">
            <a class="active">项目管理</a>
            <a href="/API/">接口管理</a>
            <a href="/Interface/">测试用例管理</a>
            <a>测试报告管理</a>
            <a>用户管理</a>
        </div>
    </div>
    <div class="home-show hide"></div>
    <div class="home-modal hide">
        <form id="project-add" class="project-form">
            <div  class="form-title">新增项目</div>
            <input type="hidden" name="project-id">
            <li>项目名称：<input type="text" name="projectname"  class="input"></li>
            <li>项目版本：<input type="text" name="projectver"   class="input"></li>
            <li>项目地址：<input type="text" name="projecturl"   class="input"></li>
            <li>项目状态：<select name="projecttype">
                        <option value="0">启用</option>
                        <option value="1">禁用</option>
                      </select>
            </li>
            <li>备注:<textarea rows="4" cols="40" name="projectremark">

            </textarea>
            </li>
            <input type="button" value="确定" class="button">
            <input type="button" value="取消" class="button">
        </form>
    </div>
    <script src="/static/js/jquery-1.12.4.js"></script>
    <script src="/static/js/project.js"></script>
</body>
</html>

templates/interface_set.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/home.css">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/common.css">
    <link rel="stylesheet" href="/static/css/interface_set.css">
</head>
<body class="home_body">
    <div class="home-header">
        <div class="user-info">{{ username }}
            <div class="user-logout">
                <a href="/logout">退出登录</a>
            </div>
        </div>
    </div>
    <div class="set_menu">
        <div class="set_menu_title"><h3>测试集合</h3></div>
        {% for x in result %}
            <div class="set_result" reslut_id={{ x.id }}>
                <a href="/Interface_set/detail/{{ x.id }}"> {{ x.reslut_name }}</a>
                <span class="edit-icon"><img src="/static/image/edit.png"></span>
                <span class="delete-icon"><img src="/static/image/delete.png"></span>
            </div>
        {% endfor %}
        <div class="set_add">+</div>
    </div>
    <div class="set_detail">
        <div class="set_header">
            <input class="btn btn-primary" type="button" value="添加用例">
            <input  class="btn btn-primary" type="button" value="开始运行">
        </div>
        <div>
            <table class="table table-striped">
                <thead>
                    <th>编号</th>
                    <th>用例名称</th>
                    <th>运行结果</th>
                    <th>运行时间</th>
                </thead>
                <tr>
                    {% for j in interface %}
                        <tr>
                            <td>{{ forloop.counter}}</td>
                            <td>{{ j.interface_name }}</td>
                            <td>{{ j.interface_rel_result }}</td>
                            <td>{{ j.create_time|date:"Y-m-d H:i:s" }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div></div>
    </div>
    <div class="home_menu">
        <div class="home-title">
           接口测试管理平台
        </div>
        <div class="home-lines">
            <a href="/project/">项目管理</a>
            <a href="/API/">接口管理</a>
            <a href="/Interface/">测试用例管理</a>
            <a class="active">测试报告管理</a>
            <a>用户管理</a>
        </div>
    </div>
    <div class="home-show hide"></div>
    <div class="add_inter hide">
        <div class="add_inter_header">
            <span>导入到集合</span>
        </div>
        <div class="set_body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th><input class="set_all" type="checkbox"></th>
                        <th>序号</th>
                        <th>用例名称</th>
                        <th>请求方式</th>
                    </tr>
                </thead>
                <tbody>
                {% for i in inter %}
                    <tr>
                        <td inter_id={{ i.id }}><input type="checkbox" name="set_inter"></td>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ i.interface_name }}</td>
                        <td>{{ i.API.get_API_way_display}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="set_bottom">
            <input type="button" class=" btn btn-primary" value="确定">
            <input type="button" class="btn" value="取消">
        </div>
    </div>
    <div class="interface-modal hide">
                <form id="set_form">
                    <div class="form-header">
                        <h4>添加集合</h4>
                    </div>
                    <div class="form-body">
                        <div class="form-content">
                            <div class="form-conetent-left">
                                <label>集合名称：</label>
                            </div>
                            <div class="form-content-right">
                                <input type="text" name="set_name">
                            </div>
                        </div>
                        <div class="form-content">
                            <div class="form-conetent-left">
                                <label>说明：</label>
                            </div>
                            <div class="form-content-right">
                                <input type="text" name="set_mark">
                                <input type="hidden" name="set_id">
                            </div>
                        </div>
                    </div>
                    <div class="form-foot">
                        <input class="btn btn-primary" type="button" value="确定">
                        <input class="btn" type="button" value="取消">
                    </div>

                </form>
            </div>
    <script src="/static/js/jquery-1.12.4.js"></script>
    <script src="/static/js/project.js"></script>
    <script src="/static/js/interface_set.js"></script>
    <script src="/static/js/detail.js"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/login.css">
    <link rel="stylesheet" href="/static/css/common.css">
</head>
<body>
<div class="login_body">
    <div class="login-alert hide"></div>
    <div class="login_form">
        <form id="login-form" >
            <div class="login-input">
                <input type="text"  class="input" name="username" placeholder="请输入用户名">
                <span class="login-icon"></span>
            </div>
            <div class="login-input">
                <input type="password" class="input" name="password" placeholder="请输入密码">
                <span class="password-icon"></span>
            </div>
            <div class="login-input">
                <input type="button"  id="login" class="login-button" value="登录">
                <input type="reset" class="login-button" value="重置">
            </div>
        </form>
    </div>
</div>
<script src="/static/js/jquery-1.12.4.js"></script>
<script src="/static/js/jquery.md5.js"></script>
<script src="/static/js/login.js"></script>
</body>
</html>

templates/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/home.css">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/common.css">
    <link rel="stylesheet" href="/static/css/user.css"
</head>
<body class="home_body">
    <div class="home-header">
        <div class="user-info">{{ username }}
            <div class="user-logout">
                <a href="/logout">退出登录</a>
            </div>
        </div>
        <div class="project-content">
            <div class="project-header">
                <span>用户名称:&nbsp&nbsp</span><input type="text" placeholder="请输入用户名称" name="query_project">
                <input type="button" value="查询" id="project-q">
                <input  class="user-new" type="button" value="新增用户" >
            </div>
            <div class="project-table">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>序号</th>
                            <th>用户名称</th>
                            <th>修改时间</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in user %}
                            <tr project-id={{ i.id }}>
                                <td>{{ forloop.counter}}</td>
                                <td>{{ i.username }}</td>
                                <td>{{ i.create_time|date:"Y.m.d" }}</td>
                                <td>
                                    <a  class="user-edit">编辑</a>
                                    <a  class="user-delete">删除</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="home-pagination">
                <span class="step-links">
                    <span class="current" >共{{ user.paginator.num_pages }}页</span>
                    {% if user.has_previous %}
                        <a href="?page={{ user.previous_page_number }}">上一页</a>
                    {% endif %}
                    <span >
                        第 {{ user.number }} 页
                    </span>
                    {% if user.has_next %}
                        <a href="?page={{ user.next_page_number }}">下一页</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
    <div class="home_menu">
        <div class="home-title">
           接口测试管理平台
        </div>
        <div class="home-lines">
            <a href="/api_project/">项目管理</a>
            <a href="/API/">接口管理</a>
            <a href="/Interface/">测试用例管理</a>
            <a href="/Interface_set/">测试报告管理</a>
            <a class="active">用户管理</a>
        </div>
    </div>
    <div class="home-show hide"></div>
    <div class="user-modal hide">
        <form id="user-add" class="project-form">
            <div  class="form-title">新增用户</div>
            <input type="hidden" name="project-id">
            <li>用户名称：<input type="text" name="projectname"  class="input"></li>
            <li>用户密码：<input type="text" name="projectver"   class="input"></li>
            <li>项目地址：<input type="text" name="projecturl"   class="input"></li>
            <input type="button" value="确定" class="button">
            <input type="button" value="取消" class="button">
        </form>
    </div>
    <script src="/static/js/jquery-1.12.4.js"></script>
    <script src="/static/js/project.js"></script>
    <script src="/static/js/user.js"></script>
</body>
</html>